namespace: awx

operator:
  helm_repo_url: "https://ansible.github.io/awx-operator/"
  helm_repo_name: "awx-operator"
  helm_chart_name: "awx-operator"
  helm_release_name: "awx-operator"

instance:
  name: awx
  admin_user: admin
  admin_pass: admin
  is_node_port: false
  node_port: 30080
  no_log: true
